export const StoreData = [
  {
    id: 1,
    name: 'samsung A13',
    img: 'img/product-1.png',
    price: 10,
    company: 'samsung',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quo suscipit odit reprehenderit eligendi magni alias voluptatem fuga eius vel sequi.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    name: 'samsung A21',
    img: 'img/product-2.png',
    price: 20,
    company: 'samsung',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    name: 'techno 4pro',
    img: 'img/product-3.png',
    price: 30,
    company: 'techno',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    name: 'techno spark 2',
    img: 'img/product-4.png',
    price: 40,
    company: 'techno',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    name: 'infinix hot 4',
    img: 'img/product-5.png',
    price: 50,
    company: 'infinix',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    name: 'Galaxy A6',
    img: 'img/product-6.png',
    price: 60,
    company: 'samsung',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    name: 'samsung Gold',
    img: 'img/product-7.png',
    price: 30,
    company: 'samsung',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    name: 'HTC 10',
    img: 'img/product-8.png',
    price: 30,
    company: 'HTC',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const testData = {
  id: 1,
  name: 'samsung A21',
  img: 'img/product-2.png',
  price: 20,
  company: 'samsung',
  desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe velit, at numquam veniam necessitatibus quibusdam eveniet cum nam doloribus. Soluta praesentium cumque eius dolore atque deserunt facere tempora ut.',
  inCart: false,
  count: 0,
  total: 0,
};
